version: "3.8"
services:
  # MongoDB Services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    container_name: nodejs-app
    build: .
    ports:
      - "3000:8000"
    environment:
      MongoDB_URL: mongodb://mongo_db:27017/music
      JWT_ACCESS_KEY: az
      JWT_REFRESH_KEY: za
      PORT: 8000
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
