version: "3.8"
services:
  # MongoDB Services
  mongo_db:
    container_name: container_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # Node API service
  nodejs-app:
    image: node:latest
    container_name: nodejs-app
    build: .
    ports:
      - "3000:5000"
    volumes:
      - ./app:/app
    environment:
      PORT: 5000
      MongoDB_URL: "mongodb://mongo_db:27017/?authMechanism=DEFAULT"

    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
