version: "4.23"

services:
  # MongoDB Services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - .:/usr/src/index
    environment:
      PORT: 5000
      MongoDB_URL: "mongodb+srv://antramcam2002:pRpNw0z2KDSzXhIH@nft.dtbancn.mongodb.net/"
      # MongoDB_URL: "mongodb://antramcam2002:pRpNw0z2KDSzXhIH@mongo_db:27017/"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
